name: epc_qr
description: EPC-QR code generator (for European SEPA transfers) in flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15 # local storage
  flutter_form_builder: ^7.4.0
  form_builder_validators: ^8.2.0
  qr_flutter: # ^4.0.0 # display qr codes
    git: https://github.com/theyakka/qr.flutter.git
  get_it: ^7.2.0 # service locator
  share_plus: ^4.0.10
  path_provider: ^2.0.11
  path: ^1.8.1
  flutter_linkify:
    git: https://github.com/madmini/flutter_linkify.git
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic