name: epc_qr
description: EPC-QR code generator (for European SEPA transfers) in flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15 # local storage
  flutter_form_builder: ^7.3.0
  form_builder_validators: ^8.1.1
  qr_flutter: ^4.0.0 # display qr codes
  get_it: ^7.2.0 # service locator
  share_plus: ^4.0.8
  path_provider: ^2.0.11

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
