name: CI

on:
  workflow_dispatch: # run from the Actions tab
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
#     container: cirrusci/flutter:stable
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
#       - uses: actions/checkout@v3

#       - name: Install dependencies
#         run: flutter pub get

#       - name: Build web
#         run: flutter build web --release --base-href "/epc-qr/"
        
#       - name: Compress web build
#         run: zip -r ../web.zip .
#         working-directory: build/web

#       - name: Store web build
#         uses: actions/upload-artifact@v3
#         with:
#           name: build-web
#           path: build/web.zip

#       - if: github.ref_type == 'tag'
#         name: Set-up GitHub Pages deployment
#         run: apt-get update && apt-get install -y rsync

#       - if: github.ref_type == 'tag'
#         name: Deploy to GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: build/web

#       - name: Build Android
#         run: flutter build apk --release

#       - name: Store android build
#         uses: actions/upload-artifact@v3
#         with:
#           name: build-android
#           path: build/app/outputs/flutter-apk/app-release.apk

#       - if: github.ref_type == 'tag'
#         name: Prepare release
#         run: |
#           mkdir artifacts
#           mv build/web.zip artifacts/epc-qr_${{ github.ref_name }}_web.zip
#           mv build/app/outputs/flutter-apk/app-release.apk artifacts/epc-qr_${{ github.ref_name }}.apk

      - name: DEBUG - prepare release
        run: |
          echo github.ref_name = ${{ github.ref_name }}
          echo github.ref_type = ${{ github.ref_type }}
          echo github.event_name = ${{ github.event_name }}
          echo github.event = ${{ github.event }}
          echo github = ${{ github }}

          mkdir artifacts
          echo ${{ github }} > artifacts/test.txt

      - #if: github.ref_type == 'tag'
        name: Create release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: artifacts/*
