name: CI

on:
  workflow_dispatch: # run from the Actions tab
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable
    concurrency: 
      group: ${{ github.workflow }}-{{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href "/epc-qr/"
      
      - #if: github.ref == 'refs/heads/main'
        name: Install rsync # for github deploy
        run: apt-get update && apt-get install -y rsync

      - #if: github.ref == 'refs/heads/main'
        name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
